export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  ANALYST = 'ANALYST',
  FIELD_OFFICER = 'FIELD_OFFICER',
  PUBLIC_USER = 'PUBLIC_USER',
  REGULATOR = 'REGULATOR',
}

export enum WaterBodyType {
  RIVER = 'RIVER',
  LAKE = 'LAKE',
  RESERVOIR = 'RESERVOIR',
  WASTEWATER = 'WASTEWATER',
  GROUNDWATER = 'GROUNDWATER',
  COASTAL = 'COASTAL',
  WETLAND = 'WETLAND',
}

export enum SensorStatus {
  ONLINE = 'ONLINE',
  OFFLINE = 'OFFLINE',
  MAINTENANCE = 'MAINTENANCE',
  FAULT = 'FAULT',
}

export enum QualityGrade {
  EXCELLENT = 'EXCELLENT',
  GOOD = 'GOOD',
  FAIR = 'FAIR',
  POOR = 'POOR',
  CRITICAL = 'CRITICAL',
}

export enum AlertStatus {
  ACTIVE = 'ACTIVE',
  ACKNOWLEDGED = 'ACKNOWLEDGED',
  RESOLVED = 'RESOLVED',
}

export enum AlertSeverity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum SatelliteSource {
  USGS_WQP = 'USGS_WQP',
  NASA_MODIS = 'NASA_MODIS',
  COPERNICUS_SENTINEL2 = 'COPERNICUS_SENTINEL2',
  COPERNICUS_SENTINEL3 = 'COPERNICUS_SENTINEL3',
  COPERNICUS_CMEMS = 'COPERNICUS_CMEMS',
}

export enum ParameterType {
  PH = 'PH',
  TURBIDITY = 'TURBIDITY',
  DISSOLVED_OXYGEN = 'DISSOLVED_OXYGEN',
  CONDUCTIVITY = 'CONDUCTIVITY',
  TEMPERATURE = 'TEMPERATURE',
  NITRATE = 'NITRATE',
  BACTERIA = 'BACTERIA',
  CHLOROPHYLL_A = 'CHLOROPHYLL_A',
  TOTAL_SUSPENDED_SOLIDS = 'TOTAL_SUSPENDED_SOLIDS',
}
